# comment
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      appname: sample
  template:
    metadata:
      labels:
        appname: sample
    spec:
      containers:
        - image: 796489341143.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app:f372cf92c6b1e562c083a4a0fb71351d765691ed
          name: sample
          ports:
            - containerPort: 5000
