# comment
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      appname: sample
  template:
    metadata:
      labels:
        appname: sample
    spec:
      containers:
        - image: 796489341143.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app:677a34edfe6e1babbba1c79dd890c9f3608bfe0c
          name: sample
          ports:
            - containerPort: 5000
