# comment
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      appname: sample
  template:
    metadata:
      labels:
        appname: sample
    spec:
      containers:
        - image: 796489341143.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app:292c447340d19d51a136287f971f45190233b736b25a855b0935a9deab7dccd317d98c1f4218963d86738a6e91f9478aca88fb83c1f84cb9f52bed36
          name: sample
          ports:
            - containerPort: 5000
