apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      appname: sample
  template:
    metadata:
      labels:
        appname: sample
    spec:
      containers:
        - image: 796489341143.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app:98f51e602853bb7a852db35bf3dc25d036238cab
          name: sample
          ports:
            - containerPort: 5000
