apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: test
  name: test-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: 796489341143.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app:f372cf92c6b1e562c083a4a0fb71351d765691ed
          name: sample-app
          ports:
            - containerPort: 5000
